### ISSUE TITLE
Game crashing when mouse is hovered over Frogbit (1.15.2)

### ISSUE THREAD

**Issue by RetroHunGamer** [mc-jt9/ProjectVibrantJourneys#113]
From crash-log:
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 8/1/20 2:55 PM
Description: Rendering screen

java.lang.IllegalArgumentException: Cannot set property IntegerProperty{name=model, clazz=class java.lang.Integer, values=[0, 1, 2, 3]} to 4 on Block{projectvibrantjourneys:frogbit}, it is not an allowed value
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at projectvibrantjourneys.common.blocks.FloatingPlantBlock.func_196258_a(FloatingPlantBlock.java:49) ~[?:1.15.2-2.0.1] {re:classloading}
	at shadows.apotheosis.ench.EnchModuleClient.tooltips(EnchModuleClient.java:45) ~[?:3.2.4] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_967_EnchModuleClient_tooltips_ItemTooltipEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:267) ~[?:?] {re:mixin,re:classloading}
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:678) ~[?:?] {re:mixin,re:classloading,xf:fml:apotheosis:apothitemusehook}
	at net.minecraft.client.gui.screen.Screen.getTooltipFromItem(Screen.java:121) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:blur:hookBackgroundColor,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.Screen.renderTooltip(Screen.java:116) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:blur:hookBackgroundColor,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.ContainerScreen.func_191948_b(ContainerScreen.java:149) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screen.inventory.InventoryScreen.render(SourceFile:95) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:368) ~[?:?] {re:classloading}
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[?:?] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:742) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:798) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:924) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:553) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) ~[1.15.2.jar:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.15.2-31.2.31.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

**Comment by ConnCraft** [comment]
Similar crash when mousing over duckweed. Not my crash, but same pack.

[message.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/5086922/message.txt)

**Comment by mnsnownutt** [comment]
> 
> 
> Similar crash when mousing over duckweed. Not my crash, but same pack.
> 
> [message.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/5086922/message.txt)

Agree.  Same issue with duckweed, crashes game in 1.15.2.

**Comment by Ridanisaurus** [comment]
I can confirm it's happening on both, and only for certain people. Here is a crash log.
https://gist.github.com/Ridanisaurus/a070a3ece36675b1b6106ec221f6f85d

**Comment by Darkere** [comment]
https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/blob/7ab6f02a85f5d7f89e06b00c07cfb9c42b0d21e3/src/main/java/projectvibrantjourneys/common/blocks/FloatingPlantBlock.java#L48

Pls fix. ;)

**Comment by hvdklauw** [comment]
[crash-2020-09-27_15.02.13-client.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/5288313/crash-2020-09-27_15.02.13-client.txt)

Just had the same :)

**Comment by krzysztofKKW** [comment]
People are crashing on my server thanks to this. Bump.
