### ISSUE TITLE
1.16.5 problem when loading or creating world with beta2

### ISSUE THREAD

**Issue by grugsy** [mc-jt9/ProjectVibrantJourneys#128]
Everything works as intended with beta1, but updating to beta2 broke something. Guessing it's a compatibility issue with modded biomes and the fallen trees? Couldn't get a crash report, but it did output a 45.56mb latest.log file. Most of it looked like the following:

[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: java.lang.NullPointerException
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList.func_234004_a_(SourceFile:42)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList$$Lambda$11486/329232102.accept(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList.func_226314_a_(SourceFile:42)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList.func_226318_b_(SourceFile:521)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.world.gen.blockstateprovider.WeightedBlockStateProvider.func_225574_a_(SourceFile:42)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at projectvibrantjourneys.init.PVJWorldGen.addFallenTreeFeatures(PVJWorldGen.java:130)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.eventbus.ASMEventHandler_286_PVJWorldGen_addFallenTreeFeatures_BiomeLoadingEvent.invoke(.dynamic)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.eventbus.EventBus$$Lambda$2562/1703034311.invoke(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.common.ForgeHooks.enhanceBiome(ForgeHooks.java:944)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.world.biome.Biome.lambda$null$8(Biome.java:75)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.world.biome.Biome$$Lambda$2146/265672341.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.util.Function8.lambda$null$6(Function8.java:22)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.util.Function8$$Lambda$11267/316623218.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.util.Function4.lambda$null$2(Function4.java:14)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.util.Function4$$Lambda$11266/323123609.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult$Instance.ap2(DataResult.java:315)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.kinds.Applicative.ap4(Applicative.java:84)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$7.decode(RecordCodecBuilder.java:404)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.MapDecoder$$Lambda$11153/1954922915.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult$$Lambda$1193/1639066642.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.Decoder.parse(Decoder.java:18)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.WorldSettingsImport$IResourceAccess$RegistryAccess.func_241879_a(WorldSettingsImport.java:236)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.WorldSettingsImport.func_241805_a_(WorldSettingsImport.java:131)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.WorldSettingsImport.func_240885_a_(WorldSettingsImport.java:105)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.WorldSettingsImport$$Lambda$11255/585964670.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult$$Lambda$1193/1639066642.apply(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.WorldSettingsImport.func_241797_a_(WorldSettingsImport.java:104)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.DynamicRegistries.func_243610_a(DynamicRegistries.java:144)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.DynamicRegistries.func_243608_a(DynamicRegistries.java:132)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.WorldSettingsImport.func_244336_a(WorldSettingsImport.java:53)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.registry.DynamicRegistries.func_239770_b_(DynamicRegistries.java:85)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.screen.CreateWorldScreen.func_243425_a(CreateWorldScreen.java:112)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.screen.WorldSelectionScreen.func_214326_e(SourceFile:54)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.screen.WorldSelectionScreen$$Lambda$11183/691740926.onPress(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper.func_198033_b(MouseHelper.java:87)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper$$Lambda$11143/1185666309.run(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper.func_228030_c_(MouseHelper.java:175)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper$$Lambda$11142/1265749190.run(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(ThreadTaskExecutor.java:106)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper.func_228028_b_(MouseHelper.java:174)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MouseHelper$$Lambda$9515/1147314184.invoke(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(SourceFile:102)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.MainWindow.func_227802_e_(MainWindow.java:398)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:996)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.client.main.Main.main(Main.java:184)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$483/668929853.call(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: java.lang.NullPointerException
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList.func_234004_a_(SourceFile:42)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList$$Lambda$11486/329232102.accept(Unknown Source)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at java.util.ArrayList.forEach(ArrayList.java:1249)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList.func_226314_a_(SourceFile:42)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.util.WeightedList.func_226318_b_(SourceFile:521)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraft.world.gen.blockstateprovider.WeightedBlockStateProvider.func_225574_a_(SourceFile:42)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at projectvibrantjourneys.init.PVJWorldGen.addFallenTreeFeatures(PVJWorldGen.java:130)
[17:35:02] [Render thread/INFO]: [net.minecraft.util.WeightedList:func_226318_b_:525]: 	at net.minecraftforge.eventbus.ASMEventHandler_286_PVJWorldGen_addFallenTreeFeatures_BiomeLoadingEvent.invoke(.dynamic)

**Comment by OrderedChaos-Dev** [comment]
From what I can tell it's because I assumed modded trees would use the same block state provider so I passed null for a parameter. I'll put up a beta3 version on curseforge with a fix that hopefully should work.

**Comment by grugsy** [comment]
It did. Worlds are loading fine with beta3. Explored some new chunks and everything seems to be generating properly from what I can tell. However, the log after seems to have some answers thanks to Blame.
[latest.log](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6134722/latest.log)

**Comment by OrderedChaos-Dev** [comment]
I've rewritten the way the fallen trees are registered which hopefully should help with mod compatibility. I've uploaded a 4th beta version to CurseForge.

**Comment by grugsy** [comment]
Working as intended, and a clean log to boot. :)
