### ISSUE TITLE
cant play because of firefly?

### ISSUE THREAD

**Issue by epicyeeto** [mc-jt9/ProjectVibrantJourneys#156]
i can't play because a firefly is loading in?

-- Entity being rendered --
Details:
	Entity Type: projectvibrantjourneys:firefly (projectvibrantjourneys.common.entities.FireflyEntity)
	Entity ID: 1311
	Entity Name: Firefly
	Entity's Exact location: -114.50, 70.00, 289.50
	Entity's Block location: World: (-115,70,289), Chunk: (at 13,4,1 in -8,18; contains blocks -128,0,288 to -113,255,303), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
	Entity NBT: {Brain:{memories:{}},HurtByTimestamp:0,Attributes:[],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,FallDistance:0.0f,CanUpdate:1b,DeathTime:0s,ForgeCaps:{"structure_gel:gel_entity":{portal:"structure_gel:empty"},"hats:capability_hat":{hsbH:0.0f,partCount:0,clrR:0.0f,count:-1,isNew:0b,hsbS:0.0f,clrG:0.0f,isShowing:0b,enchanted:0b,clrA:0.0f,clrB:0.0f,name:"",hsbB:0.0f,isFavourite:0b},"mekanism:radiation":{radiation:0.0d},"twilightforest:cap_shield":{permshields:0,tempshields:0},"mowziesmobs:frozen":{frozenYaw:0.0f,freezeProgress:0.0f,frozenPitch:0.0f,freezeDecayDelay:0,prevHasAI:1b,frozenYawHead:0.0f,frozenLimbSwingAmount:0.0f,prevFrozen:0b,frozenRenderYawOffset:0.0f,frozenSwingProgress:0.0f},"citadel:extended_entity_data_citadel":{}},HandDropChances:[0.085f,0.085f],PersistenceRequired:0b,UUID:[I;1296872987,1102857796,-1661216644,1121507066],Motion:[0.0d,0.0d,0.0d],Health:1.0f,LeftHanded:0b,Air:300s,OnGround:0b,CitadelData:{},Rotation:[-108.28125f,0.0f],HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Pos:[-114.5d,70.0d,289.5d],Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s}
-- Renderer details --
Details:
	Assigned renderer: projectvibrantjourneys.client.entity.renderers.FireflyRenderer@f931f60
	Location: 38.00,-11.62,29.00 - World: (38,-12,29), Chunk: (at 6,-1,13 in 2,1; contains blocks 32,0,16 to 47,255,31), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Rotation: -108.28125
	Delta: 0.4599096
Stacktrace:
	at net.minecraft.client.renderer.entity.EntityRendererManager.func_229084_a_(EntityRendererManager.java:251) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:twilightforest:renderer,pl:mixin:APP:sodium.mixins.json:features.entity.shadow_clipping.MixinEntityRenderDispatcher,pl:mixin:APP:notenoughcrashes.mixins.json:client.EntityRenderDispatcherMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.WorldRenderer.func_228418_a_(WorldRenderer.java:1202) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:entity_culling:SetupTerrain Transformer,xf:fml:entity_culling:UpdateCameraAndRender Transformer,xf:fml:twilightforest:render,xf:fml:chunkanimator:WorldRenderer#renderChunkLayer,xf:fml:journeymap:WorldRenderer.markForRerender,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:supplementaries.mixins.json:ParrotPartyMixin,pl:mixin:APP:betterendforge.mixins.json:WorldRendererMixin,pl:mixin:APP:structure_gel.mixins.json:WorldRendererMixin,pl:mixin:APP:sereneseasons.mixins.json:client.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.block.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.buffer_builder.intrinsics.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinWorldRenderer,pl:mixin:APP:sodium.mixins.json:features.options.MixinWorldRenderer,pl:mixin:APP:flywheel.mixins.json:CancelEntityRenderMixin,pl:mixin:APP:flywheel.mixins.json:FixFabulousDepthMixin,pl:mixin:APP:flywheel.mixins.json:RenderHooksMixin,pl:mixin:APP:citadel.mixins.json:client.WorldRendererMixin,pl:mixin:APP:appliedenergistics2.mixins.json:spatial.SkyRenderMixin,pl:mixin:A,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['EpicDeleto'/1088, l='ClientLevel', x=-152.50, y=80.00, z=260.50]]
	Chunk stats: Client Chunk Cache: 1024, 289
	Level dimension: minecraft:overworld
	Level spawn location: World: (-160,78,256), Chunk: (at 0,4,0 in -10,16; contains blocks -160,0,256 to -145,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 86 game time, 86 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:sun_brightness_client,pl:mixin:APP:sodium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:mixins.sndctrl.json:MixinClientWorld,pl:mixin:APP:betterbiomeblend.mixins.json:MixinClientWorld,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:abnormals_core.mixins.json:client.ClientWorldMixin,pl:mixin:APP:create.mixins.json:BreakProgressMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2029) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:28) [?:?] {re:mixin,re:classloading}
	at net.minecraft.client.Minecraft.modify$znk000$onCrash(Minecraft.java:5048) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.handler$znk000$afterCrashHandled(Minecraft.java:5040) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.handler$znk000$afterCrashHandled(Minecraft.java:5040) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.2.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$481/436399072.call(Unknown Source) [forge-1.16.5-36.2.2.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}

**Comment by OrderedChaos-Dev** [comment]
I need to see the full crash log

**Comment by epicyeeto** [comment]
[crash-2021-08-09_16.36.58-fml.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/6957388/crash-2021-08-09_16.36.58-fml.txt)

**Comment by OrderedChaos-Dev** [comment]
Looks like a problem with Supplementaries. It's crashing on trying to load something from Decorative Blocks that doesn't exist. Not sure where you got the fireflies part since it's not in the crash report, but I'll leave this issue up for now just in case.
FWIW, my game has Supplementaries v0.14.5 with no issues.

**Comment by epicyeeto** [comment]
yeah it is only with the new version 0.14.5 work normally

**Comment by OrderedChaos-Dev** [comment]
So everything has been fixed on your end?

**Comment by cheshyrp** [comment]
I thought fireflies were disabled by default? I tried them, but had to disable almost immediately because of issues. Unfortunately, I forget what the problem was. *blush*

**Comment by OrderedChaos-Dev** [comment]
They are not disabled by default. If you remember what the issues were, please let me know!
