### ISSUE TITLE
Crash due to IcicleBlock ( my first issues on github ^^ )

### ISSUE THREAD

**Issue by AltezaR** [mc-jt9/ProjectVibrantJourneys#197]
Time: 2023-03-22 21:44:16
Description: Exception ticking world

java.lang.NullPointerException: Cannot invoke "net.minecraft.core.BlockPos.m_122032_()" because "pos" is null
	at com.projectvibrantjourneys.common.blocks.IcicleBlock.findBlockVertical(IcicleBlock.java:378) ~[%5BE%5D%20projectvibrantjourneys-1.19.2-5.1.0.jar%23211!/:?] {re:classloading}
	at com.projectvibrantjourneys.common.blocks.IcicleBlock.findFillableCauldronBelowStalactiteTip(IcicleBlock.java:172) ~[%5BE%5D%20projectvibrantjourneys-1.19.2-5.1.0.jar%23211!/:?] {re:classloading}
	at com.projectvibrantjourneys.common.blocks.IcicleBlock.m_213898_(IcicleBlock.java:150) ~[%5BE%5D%20projectvibrantjourneys-1.19.2-5.1.0.jar%23211!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:notreepunching.common.mixins.json:AbstractBlockStateAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:360) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.projectvibrantjourneys.common.blocks.IcicleBlock.findBlockVertical(IcicleBlock.java:378) ~[%5BE%5D%20projectvibrantjourneys-1.19.2-5.1.0.jar%23211!/:?] {re:classloading}
	at com.projectvibrantjourneys.common.blocks.IcicleBlock.findFillableCauldronBelowStalactiteTip(IcicleBlock.java:172) ~[%5BE%5D%20projectvibrantjourneys-1.19.2-5.1.0.jar%23211!/:?] {re:classloading}
	at com.projectvibrantjourneys.common.blocks.IcicleBlock.m_213898_(IcicleBlock.java:150) ~[%5BE%5D%20projectvibrantjourneys-1.19.2-5.1.0.jar%23211!/:?] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222972_(BlockBehaviour.java:698) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,re:classloading,pl:mixin:APP:mixins.oculus.json:MixinBlockStateBehavior,pl:mixin:APP:notreepunching.common.mixins.json:AbstractBlockStateAccessor,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8714_(ServerLevel.java:446) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:360) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,pl:mixin:APP:snowrealmagic.mixins.json:ServerLevelMixin,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:A}
-- Affected level --
Details:
	All players: 1 total; [ServerPlayer['AltezaR'/231, l='ServerLevel[123]', x=87.63, y=63.00, z=9.85]]
	Chunk stats: 2903
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,71,0), Section: (at 0,7,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 22577 game time, 10480 day time
	Level name: 123
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 38286 (now: false), thunder time: 95656 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:classloading,pl:runtimedistcleaner:A,re:mixin,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23275!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by DanteTooMayCry** [comment]
Similar Crash:

[crash-2024-03-13_00.25.41-server.txt](https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/files/14579842/crash-2024-03-13_00.25.41-server.txt)

**Comment by OrderedChaos-Dev** [comment]
Sorry for not seeing this. Likely to fix this in 1.21 though I wasn't able to reproduce in any version with the icicle
